export const CREATE_USER_REQUEST="CREATE_USER_REQUEST"
export const CREATE_USER_SUCCESS="CREATE_USER_SUCCESS"
export const CREATE_USER_ERROR="CREATE_USER_ERROR"

export const LOGIN_USER_REQUEST="LOGIN_USER_REQUEST"
export const LOGIN_USER_SUCCESS="LOGIN_USER_SUCCESS"
export const LOGIN_USER_ERROR="LOGIN_USER_ERROR"